// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/ui/notifications.js

let toastTimer = null;

export function showToast(msg, { tone = "neutral", timeout = 5000 } = {}) {
  const t = document.getElementById("toast");
  if (!t) return;
  t.textContent = String(msg || "").trim();
  t.dataset.tone = tone;
  t.style.display = "block";
  if (toastTimer) clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    t.style.display = "none";
    delete t.dataset.tone;
    toastTimer = null;
  }, timeout);
}

export function getActionableErrorMessage(err, { context = "", fallback = "Something went wrong. Please try again." } = {}) {
  const raw = String(err?.userMessage || err?.message || err || "").replace(/\s+/g, " ").trim();
  if (!raw) return fallback;
  if (err?.userMessage) return err.userMessage;

  const lower = raw.toLowerCase();
  const mode = String(err?.mode || "").toLowerCase();
  const status = Number(err?.status || 0);
  const contextLabel = String(context || "").toLowerCase();
  const isProxyMode = mode === "proxy";
  const isDirectMode = mode === "direct";
  const isFileProtocol = typeof location !== "undefined" && location.protocol === "file:";

  if (status === 401 || /missing openrouter key|authorization|api key|sk-or-/.test(lower)) {
    if (isProxyMode) {
      return "Model authentication failed in proxy mode. Set OPENROUTER_API_KEY for the local proxy or switch to direct mode with a valid OpenRouter key, then rerun.";
    }
    return isFileProtocol
      ? "OpenRouter authentication failed. Paste a valid OpenRouter key in the setup panel and serve the app from localhost instead of file://, then rerun."
      : "OpenRouter authentication failed. Paste a valid OpenRouter key in the setup panel and rerun.";
  }

  if (status === 429 || status === 402 || /rate limit|quota|credits|payment required|too many requests/.test(lower)) {
    return "The model provider rejected the request due to rate limits or quota. Wait a minute and rerun, or switch to a smaller or cheaper model.";
  }

  if (/failed to fetch|networkerror|fetch failed|load failed|could not reach|socket|econnrefused/.test(lower)) {
    if (isProxyMode) {
      return "Could not reach the local proxy. Start `node proxy_server.mjs`, confirm the app is being served from localhost, and rerun.";
    }
    return isDirectMode && isFileProtocol
      ? "Direct mode from file:// is unreliable. Serve the app from localhost, keep a valid OpenRouter key in the setup panel, and rerun."
      : "Could not reach the model provider. Check network access and rerun.";
  }

  if (/timeout|timed out|aborted|abortsignal/.test(lower)) {
    return "The model call timed out. Rerun once, or reduce load by using Balanced or Fast quality.";
  }

  if (/response[_\s-]?format|unsupported|not supported|unknown parameter|invalid request/.test(lower)) {
    return "The selected model rejected the structured response format. Switch to a model that supports JSON-style responses and rerun.";
  }

  if (/returned no text|no text content|empty response/.test(lower)) {
    return "The model returned no usable text. Rerun once, and switch research models if it keeps happening.";
  }

  if (/could not parse json|parse failed|malformed json/.test(lower)) {
    if (contextLabel.includes("synth")) {
      return "The synthesis step returned malformed structured output. Rerun once, then try a different research model if it persists.";
    }
    if (contextLabel.includes("probe")) {
      return "A probe returned malformed structured output. Rerun once, then try a different research model if it persists.";
    }
    return "The model returned malformed structured output. Rerun once, then switch models if it persists.";
  }

  if (/embedding|vector layout|batch mismatch/.test(lower) || contextLabel.includes("embedding")) {
    return "Semantic positioning failed. The run can continue with fallback geometry, but switch embedding models or rerun if you need the semantic map.";
  }

  if (/synthesis/.test(lower) || contextLabel.includes("synth")) {
    return "The synthesis step failed. The run can continue with fallback synthesis, but rerun or switch research models if the result looks thin.";
  }

  if (/probe/.test(lower) || contextLabel.includes("probe")) {
    return "One or more probes failed. Check your model settings and key, then rerun for full coverage.";
  }

  return raw || fallback;
}

export function showActionableError(err, options = {}) {
  const message = getActionableErrorMessage(err, options);
  showToast(message, { tone: "error", timeout: 8000, ...options });
  return message;
}

export function setProbeState(id,state,statusText){const dot=document.getElementById(`dot-${id}`);const status=document.getElementById(`status-${id}`);const item=dot?.closest(".probe-item");if(!dot||!status||!item) return;dot.className=`probe-dot ${state}`;item.className=`probe-item ${state}`;status.textContent=statusText;}
