import { API_ENDPOINTS } from '../core/constants.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/api/provider.js

export function normalizeMode(cfg){return cfg?.mode==="proxy"?"proxy":"direct";}

export function endpointFor(kind,cfg){const modeCfg=API_ENDPOINTS[normalizeMode(cfg)]||API_ENDPOINTS.direct;return modeCfg[kind];}

function parseErrorBody(raw){try{const parsed=JSON.parse(raw);if(typeof parsed?.error==="string") return parsed.error;if(typeof parsed?.error?.message==="string") return parsed.error.message;if(typeof parsed?.detail==="string") return parsed.detail;if(typeof parsed?.message==="string") return parsed.message;}catch{}return String(raw||"").trim();}

function buildProviderError(kind,mode,status,raw){const message=parseErrorBody(raw).slice(0,500)||"Unknown provider error.";const err=new Error(`${kind} request failed (${status}): ${message}`);err.kind=kind;err.mode=mode;err.status=status;err.rawBody=raw;return err;}

export async function providerFetch(kind,body,cfg){const headers={"Content-Type":"application/json"};const mode=normalizeMode(cfg);if(cfg.apiKey){headers["Authorization"]=`Bearer ${cfg.apiKey}`;}if(mode==="direct"){headers["HTTP-Referer"]=location.origin&&location.origin!=="null"?location.origin:"https://parallax.local";headers["X-Title"]="Parallax";}let response;try{response=await fetch(endpointFor(kind,cfg),{method:"POST",headers,body:JSON.stringify(body)});}catch(err){const wrapped=new Error(`${kind} request failed: ${err?.message||err}`);wrapped.kind=kind;wrapped.mode=mode;wrapped.cause=err;throw wrapped;}if(!response.ok){const raw=(await response.text()).slice(0,1200);throw buildProviderError(kind,mode,response.status,raw);}return response.json();}
