import { DISCS, TERMS } from '../core/state.js';
import { toCanonicalKey } from './aliases.js';
import { getLinkedCitationsForTerm } from './citations.js';
import { clamp01 } from '../plot/plot-overlays.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/domain/grounding-status.js

export function getProbeCount(){return Math.max(1,DISCS.length||1);}

export function computeTermRelevanceScore(term){
  const centrality=clamp01(Number(term?.centrality??0.5));
  const sliceCount=Array.isArray(term?.slices)?term.slices.length:0;
  const probeCount=getProbeCount();
  const probeCoverage=term?.type==="emergent"&&sliceCount===0?0.65:clamp01(sliceCount/probeCount);
  const recurrence=clamp01(sliceCount<=1?0:(sliceCount-1)/Math.max(1,probeCount-1));
  const typeSignal=term?.type==="contradictory"?0.98:term?.type==="convergent"?0.95:term?.type==="emergent"?0.86:0.56;
  return Number(clamp01((centrality*0.46)+(probeCoverage*0.24)+(recurrence*0.14)+(typeSignal*0.16)).toFixed(3));
}

export function computeTermEvidenceSupportScore(term){
  const citations=getLinkedCitationsForTerm(term);
  const count=citations.length;
  const researchSignal=count?Math.min(1,count/3):0;
  const sourceDiversityCount=new Set(citations.map(c=>String(c?.source_type||"").trim().toLowerCase()||"untyped")).size;
  const sourceDiversity=count?Math.min(1,sourceDiversityCount/Math.min(3,count)):0;
  const sliceCount=Array.isArray(term?.slices)?term.slices.length:0;
  const probeCoverage=clamp01(sliceCount/getProbeCount());
  const structureSignal=term?.type==="convergent"||term?.type==="contradictory"?Math.max(probeCoverage,0.72):term?.type==="emergent"?0.58:probeCoverage;
  return Number(clamp01((researchSignal*0.68)+(sourceDiversity*0.12)+(structureSignal*0.2)).toFixed(3));
}

export function termScoreBand(score){
  const val=Number(score);
  if(!Number.isFinite(val)) return "low";
  if(val>=0.72) return "high";
  if(val>=0.48) return "medium";
  return "low";
}

export function getTermSignalModel(term){
  const relevanceScore=computeTermRelevanceScore(term);
  const evidenceSupportScore=computeTermEvidenceSupportScore(term);
  const relevanceBand=termScoreBand(relevanceScore);
  const evidenceBand=termScoreBand(evidenceSupportScore);
  const citationCount=getLinkedCitationsForTerm(term).length;
  const probeMentions=Array.isArray(term?.slices)?term.slices.length:0;
  const displayDescriptionSource=String(term?.description_source||"").trim().toLowerCase()||"unknown";
  return {relevanceScore,evidenceSupportScore,relevanceBand,evidenceBand,citationCount,probeMentions,displayDescriptionSource};
}

export function refreshTermSignalFields(terms=TERMS){
  for(const term of (Array.isArray(terms)?terms:[])){
    if(!term||typeof term!=="object") continue;
    const signal=getTermSignalModel(term);
    term.relevance_score=signal.relevanceScore;
    term.evidence_support_score=signal.evidenceSupportScore;
    term.display_description_source=signal.displayDescriptionSource;
  }
}
